SET
SEARCH_PATH TO BOARD_PROJECT;

CREATE TABLE MEMBER
(
    ID          VARCHAR(20),
    PASSWORD    VARCHAR(50)        NOT NULL,
    NAME        VARCHAR(3)         NOT NULL,
    EMAIL       VARCHAR(30)        NOT NULL,
    PHONE       VARCHAR(13)        NOT NULL,
    POST_CODE   INTEGER NULL,
    ADDR        VARCHAR(30) NULL,
    DETAIL_ADDR VARCHAR(30) NULL,
    REG_DATE    DATE DEFAULT NOW() NOT NULL
);

DROP TABLE MEMBER;